baseURL = 'https://stuffbymax.me/'
languageCode = 'en'
title = ''
theme = "PaperMod"

# Metadata
[params]
  author = "stuffbymax"
  description = "A personal website built with Hugo."
  keywords = ["Hugo", "Portfolio", "Personal Website"]

# Menu Configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
    


